### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by jakeStoneDev** [jakeStoneDev/driving-game.#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [ ] ...

**Comment by jakeStoneDev** [comment]
<ul>
    <li><input type="checkbox" value="add a canvas tag into the html document"></li>
  </ul>`

**Comment by jakeStoneDev** [comment]
- [ ] Add a <canvas> tag to the HTML document

- [ ] set parameters of the canvas so it appears as desired
- [ ] place border around the canvas
- [ ] On window load, create a new instance of image 
- [ ] place a jpg image of car onto the canvas at (x,y) > (0,0)
