### ISSUE TITLE
User can turn their car #2

### ISSUE THREAD

**Issue by jakeStoneDev** [jakeStoneDev/driving-game.#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ] ...

**Comment by jakeStoneDev** [comment]
- [ ] using the set image, draw a single page
- [ ] draw new page that sets car rotation using the w,s,d,a keys
- [ ] allow this process to repeat like a flip-book
- [ ] car should rotate but not move, and the drawing should update every time
