### ISSUE TITLE
User can start their car #3

### ISSUE THREAD

**Issue by jakeStoneDev** [jakeStoneDev/driving-game.#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] ...

**Comment by jakeStoneDev** [comment]
- [ ]the rotation set on the car should stay the same when spacebar is pressed
- [ ]car should move in the direction it was last facing for a set amount of pixels
- [ ] page should update the location of the car and place the image in set location
