### ISSUE TITLE
User can stop their car #4

### ISSUE THREAD

**Issue by jakeStoneDev** [jakeStoneDev/driving-game.#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [ ] ...

**Comment by jakeStoneDev** [comment]
- [ ] Once car has reached the target location, the car should stop and the page should update its location.
- [ ] car must maintain angle it was facing.
- [ ] car must stop before exiting page
- [ ] car must continue in the direction is was facing when it stopped
