### ISSUE TITLE
User can steer their car #5

### ISSUE THREAD

**Issue by jakeStoneDev** [jakeStoneDev/driving-game.#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [ ] ...

**Comment by jakeStoneDev** [comment]
- [ ] while car is traveling, if arrow keys are pressed alter the direction and continue for the remaining distance
- [ ] car should set reset its angle to be set to the new course
- [ ] car should not travel a different difference
